### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by SrGatoo** [wabbitguy/Kobra_Max#16]
If you go into the language settings, the screen goes blank and you don't even have the option to go back.

Not that is that important, but maybe removing the option or enabling 3-4 languages in marlin could be nice.

**Comment by maikramer** [comment]
Language screen was replaced by printer stats. You must flash the DWIN_SET from the release to your touch. Then you will see Printer Stats, not Language.
Is not like this to add languages, for adding a language, all the pages need to be reworked with the new language. Or, a complete rework of the lcd firmware to suporte dynamic languages.
