### ISSUE TITLE
Revo Six Version possible ?

### ISSUE THREAD

**Issue by DrPerry97** [wabbitguy/Kobra_Max#17]
Hello,
I tried to use your version with my kobra max and getting some problem with temperature and flow. 
After several mails with E3D we found the problem. The Revo Six uses a different sensor. 
So I must change the configure.h file. No problem. 
After the changes : 
#define TEMP_SENSOR_0 5
#define HEATER_0_MAXTEMP 300

I tried to compile it with visual code and platformio. And crashing every, after 6 hours of trying. 
Is it possible that you could build the your version with these changes ? 
I have no idea what I can try to get it run.

**Comment by maikramer** [comment]
You cant use platformio, you must build using Keil, is not that hard.
Just follow here:
https://www.reddit.com/r/anycubic/comments/y2waxu/tutorial_how_to_build_anycubic_marlin_source_code/

Or: you can wait until i finish my work on having a updated Marlin for the Kobra Max. I'm almost there.
You can build it with platformio and vs code.
https://github.com/maikramer/MarlinKobraMax
I still working on it, but the only things are not working are the runout sensor and the Power Loss recovery.
With my build you can use the updated Linear Advance and the much improved Input Shapping.
