### ISSUE TITLE
Has ANYONE had any issues updating screen FW? No matter what I do, it just boots to splash screen

### ISSUE THREAD

**Issue by TTVert** [wabbitguy/Kobra_Max#19]
Board FW boots fine.   I am powering on the printer w/ the DWIN_SET folder and its contents off of the root of the SD card.  I have tried 3 different 8GB SD cards and have tried formatting in FAT32, NTFS AND exfat but nothing seems to work when inserting into the screen SD card slot.  The same cards can read GCODE (as well as updated board FW fine) when inserted into the main board SD card slot so I know the card formatting is acceptable to the printer.  As a sanity check I even obtained the stock screen firmware off anycubics site and install but same deal, it's like the screen sd card reader is not seeing the SD card.  I know this isn't an issue you guys can directly resolve but curious if anyone has any input as to how I could test to see if the screen sd card is actually reading the cards.  It always just instantly boots up to the splash screen, bypassing the blue screen to update.

Any input would be great. 
Thanks
Dave

**Comment by maikramer** [comment]
If you downloaded the DWIN_SET from this repository, you will see that there is a DWIN_SET inside the DWIN_SET repository, copy this DWIN_SET inside to your sd card.

**Comment by TTVert** [comment]
> If you downloaded the DWIN_SET from this repository, you will see that there is a DWIN_SET inside the DWIN_SET repository, copy this DWIN_SET inside to your sd card.

Yes, I know there is a a DWIN_SET folder w/in the zip that has to be extracted to root.  The folder is right off of the root of SD Card

Dave

**Comment by TTVert** [comment]
Turns out i have a TJC screen and perhaps that needs a differently complied version than the DWIN? If I rename that DWIN_SET folder to TJC_SET it'll at least boot to a white screen which is progress.

Dave
