### ISSUE TITLE
Changes for direct drive extruder as promised.

### ISSUE THREAD

**Issue by zebrabunny** [wabbitguy/Kobra_Max#25]
I decided to basically skip the high speed part of the feed (which would not feed properly with the smaller motor anyway) the shorter low speed part was more than enough. I let it feed plenty to purge the old color. From barely engaged in the extruder to output at the nozzle is 5 inches.

thanks for your work on things

**Comment by wabbitguy** [comment]
@zebrabunny awesome to hear you got it flying and happy to have helped in any way!

Mel
