### ISSUE TITLE
Problema LCD kobra Max DWINSET 

### ISSUE THREAD

**Issue by diegofdt99** [wabbitguy/Kobra_Max#27]
Hola.

He actualizado FW de kobra Max pero no reconoce el texto. El texto es invisible, el resto funciona muy bien. Que puedo hacer? He vuelto a versión original de la pagina de anycubic y me pasa lo mismo. En dwinset estoy incorporando 4 archivos:
13 touchfile
14 showfile.bin
16_68_
22.Config.bim

Si pongo los jpg. Y resto de archivos como en fw oficial el fw no carga y aparece pantalla en negro al iniciar.

Agradecería mucho tu ayuda. Un saludo

**Comment by wabbitguy** [comment]
@diegofdt99 if you have the new motherboard and LCD display, the firmware for the printer and display here will not work.
