### ISSUE TITLE
Help! Supports are not printed

### ISSUE THREAD

**Issue by GennadijStasyuk** [wabbitguy/Kobra_Max#28]
Good afternoon!!! My name is Gennady! I have a question for you! I downloaded your ABS settings for the KOBRA MAX printer, but now I have stopped generating support and it is impossible to disable BRIM((((Please help, I'm new to this))) By the way, your settings are just perfect for printing!!! Thank you!
![1](https://github.com/wabbitguy/Kobra_Max/assets/158597506/26125cf9-cec9-413d-9b3c-34781de832ab)

**Comment by wabbitguy** [comment]
@GennadijStasyuk wow..there's something goofy going on with Github, I never even saw this issue open until today. I'd imagine you have figured it out by now.. I hope.

Mel
