### ISSUE TITLE
Link ist Broken

### ISSUE THREAD

**Issue by marcuswitt** [wabbitguy/Kobra_Max#3]
.... https://github.com/malebuffy/Kobra-Max-Cobra-Kai-UI-and-Firmware?fbclid=IwAR3UOyf4lHuyn_3JxBvaCf0rS0fiHFKiGbekmzN2qLTCZZoNCueDQDiI9J8](https://github.com/wabbitguy/Kobra_Max/blob/V1.5/url .... not working

**Comment by wabbitguy** [comment]
Fixed now.
