### ISSUE TITLE
[FR] PID tuning

### ISSUE THREAD

**Issue by n1k0-83** [wabbitguy/Kobra_Max#9]
Would it be possible to integrate automatic PID tuning into the firmware?
I know this personally from the modified community firmware of the Vyper: https://github.com/CR6Community

**Comment by wabbitguy** [comment]
@n1k0-83 PID tuning is a waste of time unless the temperature oscillates more that +-2C once it's reached it's target temperature. Trying to fix a substandard thermistor with firmware is counter productive. Just replace the thing with a quality part.

For PID tuning, the Kobra Max does that now with Pronterface or a host connected and gives the settings it thinks might work in the terminal. Write those down, power cycle the printer, then use the M301 GCODE to send them to the printer and M500 to save them.
